name: Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  #on PR merge into main branche and run the jobs

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2   # we are using the checkout repository to performe an action. (githb.com/actions) here we can see all repositories
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2 # use the library to setup the type of app we are using (python, go, ruby etc.)
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run test
